### ISSUE TITLE
ReferenceError: webkitRTCPeerConnection is not defined

### ISSUE THREAD

**Issue by vimal-hoh** [MrJaeger/Hydra#1]
ReferenceError: webkitRTCPeerConnection is not defined

peerConnection = new webkitRTCPeerConnection(null);

hydra-client.js (line 163, col 7)

**Comment by MrJaeger** [comment]
Added support for Firefox using `RTCPeerConnection`.  Currently only Chrome and Firefox support WebRTC so please use one of those browsers if youd like to run the demo/use this code!
